id: 599b778c-add3-455f-8554-4fb39c925f11
title: Sweetmini 1080p
subtitle: FXAA Off - Includes FSR and DynRes Disabler
description:
version: 1.0.0
category: 2
game:
  titleId: 0100F2C011586000
  version:
    - 1.1.2
emulator:
  - 1
compatibility:
  whitelist:
  blacklist:
    - 0ef8f231-8d97-486e-bfa1-e40f578eed9d
    - d356a7a2-4e8f-4187-8321-7f4d56d1a2f6
author: 
  - { name: Sweetmini, link: }

